(cl:defpackage uav_msgs-msg
  (:use )
  (:export
   "<CAMERAINFOEXTENDED>"
   "CAMERAINFOEXTENDED"
   "<DZPOSITION>"
   "DZPOSITION"
   "<LIDARSREADINGS>"
   "LIDARSREADINGS"
   "<MISSIONPARAMS>"
   "MISSIONPARAMS"
   "<PAYLOADPOSITION>"
   "PAYLOADPOSITION"
   "<PAYLOADROI>"
   "PAYLOADROI"
   "<PRECLAND>"
   "PRECLAND"
   "<PRECLOIT>"
   "PRECLOIT"
   "<READQR>"
   "READQR"
  ))

