// Generated by gencpp from file uav_msgs/DetectQRResponse.msg
// DO NOT EDIT!


#ifndef UAV_MSGS_MESSAGE_DETECTQRRESPONSE_H
#define UAV_MSGS_MESSAGE_DETECTQRRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_msgs
{
template <class ContainerAllocator>
struct DetectQRResponse_
{
  typedef DetectQRResponse_<ContainerAllocator> Type;

  DetectQRResponse_()
    : scanQR(false)
    , data()  {
    }
  DetectQRResponse_(const ContainerAllocator& _alloc)
    : scanQR(false)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _scanQR_type;
  _scanQR_type scanQR;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::uav_msgs::DetectQRResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::DetectQRResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DetectQRResponse_

typedef ::uav_msgs::DetectQRResponse_<std::allocator<void> > DetectQRResponse;

typedef boost::shared_ptr< ::uav_msgs::DetectQRResponse > DetectQRResponsePtr;
typedef boost::shared_ptr< ::uav_msgs::DetectQRResponse const> DetectQRResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_msgs::DetectQRResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_msgs::DetectQRResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_msgs::DetectQRResponse_<ContainerAllocator1> & lhs, const ::uav_msgs::DetectQRResponse_<ContainerAllocator2> & rhs)
{
  return lhs.scanQR == rhs.scanQR &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_msgs::DetectQRResponse_<ContainerAllocator1> & lhs, const ::uav_msgs::DetectQRResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::DetectQRResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::DetectQRResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::DetectQRResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::DetectQRResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::DetectQRResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::DetectQRResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::DetectQRResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9fc7dd8665eb3444a8a53a262d3cf78";
  }

  static const char* value(const ::uav_msgs::DetectQRResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9fc7dd8665eb344ULL;
  static const uint64_t static_value2 = 0x4a8a53a262d3cf78ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::DetectQRResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_msgs/DetectQRResponse";
  }

  static const char* value(const ::uav_msgs::DetectQRResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::DetectQRResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool scanQR\n"
"string data\n"
"\n"
;
  }

  static const char* value(const ::uav_msgs::DetectQRResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_msgs::DetectQRResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.scanQR);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectQRResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::DetectQRResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_msgs::DetectQRResponse_<ContainerAllocator>& v)
  {
    s << indent << "scanQR: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.scanQR);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_DETECTQRRESPONSE_H
