// Generated by gencpp from file uav_msgs/ReadQR.msg
// DO NOT EDIT!


#ifndef UAV_MSGS_MESSAGE_READQR_H
#define UAV_MSGS_MESSAGE_READQR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace uav_msgs
{
template <class ContainerAllocator>
struct ReadQR_
{
  typedef ReadQR_<ContainerAllocator> Type;

  ReadQR_()
    : data()
    , location()  {
    }
  ReadQR_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , location(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _location_type;
  _location_type location;





  typedef boost::shared_ptr< ::uav_msgs::ReadQR_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::ReadQR_<ContainerAllocator> const> ConstPtr;

}; // struct ReadQR_

typedef ::uav_msgs::ReadQR_<std::allocator<void> > ReadQR;

typedef boost::shared_ptr< ::uav_msgs::ReadQR > ReadQRPtr;
typedef boost::shared_ptr< ::uav_msgs::ReadQR const> ReadQRConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_msgs::ReadQR_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_msgs::ReadQR_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_msgs::ReadQR_<ContainerAllocator1> & lhs, const ::uav_msgs::ReadQR_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.location == rhs.location;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_msgs::ReadQR_<ContainerAllocator1> & lhs, const ::uav_msgs::ReadQR_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::ReadQR_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::ReadQR_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::ReadQR_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::ReadQR_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::ReadQR_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::ReadQR_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::ReadQR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b97356b914a0ea80b810a8e728c804b";
  }

  static const char* value(const ::uav_msgs::ReadQR_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b97356b914a0ea8ULL;
  static const uint64_t static_value2 = 0x0b810a8e728c804bULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::ReadQR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_msgs/ReadQR";
  }

  static const char* value(const ::uav_msgs::ReadQR_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::ReadQR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string data\n"
"#offset in meters\n"
"geometry_msgs/Point[] location\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::uav_msgs::ReadQR_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_msgs::ReadQR_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadQR_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::ReadQR_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_msgs::ReadQR_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
    s << indent << "location[]" << std::endl;
    for (size_t i = 0; i < v.location.size(); ++i)
    {
      s << indent << "  location[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.location[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_READQR_H
