// Generated by gencpp from file uav_msgs/SetCurrent.msg
// DO NOT EDIT!


#ifndef UAV_MSGS_MESSAGE_SETCURRENT_H
#define UAV_MSGS_MESSAGE_SETCURRENT_H

#include <ros/service_traits.h>


#include <uav_msgs/SetCurrentRequest.h>
#include <uav_msgs/SetCurrentResponse.h>


namespace uav_msgs
{

struct SetCurrent
{

typedef SetCurrentRequest Request;
typedef SetCurrentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCurrent
} // namespace uav_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uav_msgs::SetCurrent > {
  static const char* value()
  {
    return "65058a332cdf9eddf11f34077a0b92a4";
  }

  static const char* value(const ::uav_msgs::SetCurrent&) { return value(); }
};

template<>
struct DataType< ::uav_msgs::SetCurrent > {
  static const char* value()
  {
    return "uav_msgs/SetCurrent";
  }

  static const char* value(const ::uav_msgs::SetCurrent&) { return value(); }
};


// service_traits::MD5Sum< ::uav_msgs::SetCurrentRequest> should match
// service_traits::MD5Sum< ::uav_msgs::SetCurrent >
template<>
struct MD5Sum< ::uav_msgs::SetCurrentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uav_msgs::SetCurrent >::value();
  }
  static const char* value(const ::uav_msgs::SetCurrentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_msgs::SetCurrentRequest> should match
// service_traits::DataType< ::uav_msgs::SetCurrent >
template<>
struct DataType< ::uav_msgs::SetCurrentRequest>
{
  static const char* value()
  {
    return DataType< ::uav_msgs::SetCurrent >::value();
  }
  static const char* value(const ::uav_msgs::SetCurrentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uav_msgs::SetCurrentResponse> should match
// service_traits::MD5Sum< ::uav_msgs::SetCurrent >
template<>
struct MD5Sum< ::uav_msgs::SetCurrentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uav_msgs::SetCurrent >::value();
  }
  static const char* value(const ::uav_msgs::SetCurrentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_msgs::SetCurrentResponse> should match
// service_traits::DataType< ::uav_msgs::SetCurrent >
template<>
struct DataType< ::uav_msgs::SetCurrentResponse>
{
  static const char* value()
  {
    return DataType< ::uav_msgs::SetCurrent >::value();
  }
  static const char* value(const ::uav_msgs::SetCurrentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UAV_MSGS_MESSAGE_SETCURRENT_H
