// Generated by gencpp from file uav_msgs/DzPosition.msg
// DO NOT EDIT!


#ifndef UAV_MSGS_MESSAGE_DZPOSITION_H
#define UAV_MSGS_MESSAGE_DZPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_msgs
{
template <class ContainerAllocator>
struct DzPosition_
{
  typedef DzPosition_<ContainerAllocator> Type;

  DzPosition_()
    : dist_x(0.0)
    , dist_y(0.0)  {
    }
  DzPosition_(const ContainerAllocator& _alloc)
    : dist_x(0.0)
    , dist_y(0.0)  {
  (void)_alloc;
    }



   typedef double _dist_x_type;
  _dist_x_type dist_x;

   typedef double _dist_y_type;
  _dist_y_type dist_y;





  typedef boost::shared_ptr< ::uav_msgs::DzPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::DzPosition_<ContainerAllocator> const> ConstPtr;

}; // struct DzPosition_

typedef ::uav_msgs::DzPosition_<std::allocator<void> > DzPosition;

typedef boost::shared_ptr< ::uav_msgs::DzPosition > DzPositionPtr;
typedef boost::shared_ptr< ::uav_msgs::DzPosition const> DzPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_msgs::DzPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_msgs::DzPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_msgs::DzPosition_<ContainerAllocator1> & lhs, const ::uav_msgs::DzPosition_<ContainerAllocator2> & rhs)
{
  return lhs.dist_x == rhs.dist_x &&
    lhs.dist_y == rhs.dist_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_msgs::DzPosition_<ContainerAllocator1> & lhs, const ::uav_msgs::DzPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::DzPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::DzPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::DzPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::DzPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::DzPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::DzPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::DzPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "548475a5e014d2e321e9481e359821fc";
  }

  static const char* value(const ::uav_msgs::DzPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x548475a5e014d2e3ULL;
  static const uint64_t static_value2 = 0x21e9481e359821fcULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::DzPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_msgs/DzPosition";
  }

  static const char* value(const ::uav_msgs::DzPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::DzPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 dist_x\n"
"float64 dist_y\n"
;
  }

  static const char* value(const ::uav_msgs::DzPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_msgs::DzPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dist_x);
      stream.next(m.dist_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DzPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::DzPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_msgs::DzPosition_<ContainerAllocator>& v)
  {
    s << indent << "dist_x: ";
    Printer<double>::stream(s, indent + "  ", v.dist_x);
    s << indent << "dist_y: ";
    Printer<double>::stream(s, indent + "  ", v.dist_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_DZPOSITION_H
