// Generated by gencpp from file uav_msgs/PilotOverride.msg
// DO NOT EDIT!


#ifndef UAV_MSGS_MESSAGE_PILOTOVERRIDE_H
#define UAV_MSGS_MESSAGE_PILOTOVERRIDE_H

#include <ros/service_traits.h>


#include <uav_msgs/PilotOverrideRequest.h>
#include <uav_msgs/PilotOverrideResponse.h>


namespace uav_msgs
{

struct PilotOverride
{

typedef PilotOverrideRequest Request;
typedef PilotOverrideResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PilotOverride
} // namespace uav_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uav_msgs::PilotOverride > {
  static const char* value()
  {
    return "019550d9794152b525bf949a5e4ab378";
  }

  static const char* value(const ::uav_msgs::PilotOverride&) { return value(); }
};

template<>
struct DataType< ::uav_msgs::PilotOverride > {
  static const char* value()
  {
    return "uav_msgs/PilotOverride";
  }

  static const char* value(const ::uav_msgs::PilotOverride&) { return value(); }
};


// service_traits::MD5Sum< ::uav_msgs::PilotOverrideRequest> should match
// service_traits::MD5Sum< ::uav_msgs::PilotOverride >
template<>
struct MD5Sum< ::uav_msgs::PilotOverrideRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uav_msgs::PilotOverride >::value();
  }
  static const char* value(const ::uav_msgs::PilotOverrideRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_msgs::PilotOverrideRequest> should match
// service_traits::DataType< ::uav_msgs::PilotOverride >
template<>
struct DataType< ::uav_msgs::PilotOverrideRequest>
{
  static const char* value()
  {
    return DataType< ::uav_msgs::PilotOverride >::value();
  }
  static const char* value(const ::uav_msgs::PilotOverrideRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uav_msgs::PilotOverrideResponse> should match
// service_traits::MD5Sum< ::uav_msgs::PilotOverride >
template<>
struct MD5Sum< ::uav_msgs::PilotOverrideResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uav_msgs::PilotOverride >::value();
  }
  static const char* value(const ::uav_msgs::PilotOverrideResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_msgs::PilotOverrideResponse> should match
// service_traits::DataType< ::uav_msgs::PilotOverride >
template<>
struct DataType< ::uav_msgs::PilotOverrideResponse>
{
  static const char* value()
  {
    return DataType< ::uav_msgs::PilotOverride >::value();
  }
  static const char* value(const ::uav_msgs::PilotOverrideResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UAV_MSGS_MESSAGE_PILOTOVERRIDE_H
