plugin_blacklist:
# common
- actuator_control
- ftp
- safety_area
- hil
# extras
#- altitude
#- distance_sensor
- debug_value
- image_pub
- px4flow
- rangefinder
- vibration
#- vision_speed_estimate	PERLU!!
#- wheel_odometry

plugin_whitelist: []
#- 'sys_*'
