(cl:defpackage uav_msgs-srv
  (:use )
  (:export
   "DETECTOBJECT"
   "<DETECTOBJECT-REQUEST>"
   "DETECTOBJECT-REQUEST"
   "<DETECTOBJECT-RESPONSE>"
   "DETECTOBJECT-RESPONSE"
   "DETECTQR"
   "<DETECTQR-REQUEST>"
   "DETECTQR-REQUEST"
   "<DETECTQR-RESPONSE>"
   "DETECTQR-RESPONSE"
   "PILOTOVERRIDE"
   "<PILOTOVERRIDE-REQUEST>"
   "PILOTOVERRIDE-REQUEST"
   "<PILOTOVERRIDE-RESPONSE>"
   "PILOTOVERRIDE-RESPONSE"
   "SETCURRENT"
   "<SETCURRENT-REQUEST>"
   "SETCURRENT-REQUEST"
   "<SETCURRENT-RESPONSE>"
   "SETCURRENT-RESPONSE"
  ))

